name: Run Terminus Command

on:
  schedule:
    - cron:  '*/5 * * * *'

env:
  KNOWN_HOSTS: 127.0.0.1
  SSH_CONFIG: |
    Host *.drush.in
      StrictHostKeyChecking no

jobs:
  terminus-drush-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploying code
        run: |
          echo "Known Hosts is $KNOWN_HOSTS"
          echo "SSH config is $SSH_CONFIG"
      - uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.PANTHEON_SSH_KEY }}
          config: ${{ env.SSH_CONFIG }}
          known_hosts: ${{ env.KNOWN_HOSTS }}
      - name: Install Terminus
        uses: ackama/setup-terminus@main
        with:
          pantheon-machine-token: ${{ secrets.PANTHEON_MACHINE_TOKEN }}
      - name: Running simple drush command
        run: terminus drush nated9.dev version